### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I noticed these things in the context of another change that I'll discuss separately.

**Comment by waywardmonkeys** [comment]
Any thoughts on either of these changes?

**Comment by antoyo** [comment]
Sorry, I haven't had the time to check yet.
I'll check these changes in the following days.
Thank you for your contribution.

**Comment by antoyo** [comment]
Thanks.

**Pull request merged**
